name: test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test
      - name: Notify on Failure
        if: failure()
        run: >
          curl -X POST https://notify-me-you-idiot.daddy.cat/
          -H "Content-Type: application/json"
          -H ${{ secrets.SECRET_HEADER }}
          -d '{"status": "failure", "message": "Test failed"}'
      - name: Notify on Success
        if: success()
        run: >
          curl -X POST https://notify-me-you-idiot.daddy.cat/
          -H "Content-Type: application/json"
          -H ${{ secrets.SECRET_HEADER }}
          -d '{"status": "success", "message": "Test passed"}'
